Use resource definition to allow multiple instances of StatsD
- Move statsd installation into resource statsd::instance
- Install an initscript for each instance
- Rename some variables for better readability
- Rename localConfig.js to config.js
- Include hostname in prefixStats
- Do not check process name on stop

diff --git a/files/statsd-wrapper b/files/statsd-wrapper
--- a/files/statsd-wrapper
+++ b/files/statsd-wrapper
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 if [ "$#" -lt 2 ]; then
   echo "Usage: $(basename $0) /path/to/stats.js /path/to/configfile path/to/logfile" >&2
@@ -9,26 +9,25 @@ STATSJS=$1
 CONFIGFILE=$2
 LOGFILE=$3
 
-
 NODE=$(which nodejs || which node)
 
-if ! [ -x "$NODE" ]; then
+if ! [ -x "${NODE}" ]; then
   echo "Unable to run node  '${NODE}' cannot be executed" >&2
   exit 255
 fi
 
-if ! [ -r "$STATSJS" ]; then
-  echo "Unable to read '$STATSJS' - file is either missing or unreadable"
+if ! [ -r "${STATSJS}" ]; then
+  echo "Unable to read '{$STATSJS}' - file is either missing or unreadable"
   exit 255
 fi
 
-if ! [ -r "$CONFIGFILE" ]; then
-  echo "Unable to read '$CONFIGFILE' - file is either missing or unreadable"
+if ! [ -r "${CONFIGFILE}" ]; then
+  echo "Unable to read '${CONFIGFILE}' - file is either missing or unreadable"
   exit 255
 fi
 
 exec 3>&2
-if [ -n "$LOGFILE" ]; then
+if [ -n "${LOGFILE}" ]; then
   exec 1>>$LOGFILE
   exec 2>>$LOGFILE
 fi
